name: "auto_gen_bind_pr"
description: "bindコードを生成するためのCIアクションをしてPRを送る"
inputs:
  build_target:
    description: "cargo build target"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: install build_target
      run: rustup target add ${{ inputs.build_target }}
      shell: bash
    - name: gen bind
      run: cargo build --target ${{ inputs.build_target }} --features generate-bindings
      shell: bash
    - name: git add
      run: git add --all
      shell: bash
    - name: check
      run: git status -s | grep -E "M|A"
      shell: bash
    - name: new_branch
      if: success()
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated generate bindings for ${{ inputs.build_target }}
