name: gen_bind
on:
  push:
    paths:
      - "onnxruntime-sys/build.rs"
jobs:
  generate_bind_x86_64_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: ./.github/actions/auto_gen_bind_pr
        with:
          build_target: x86_64-unknown-linux-gnu
  generate_bind_x86_64_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: x86_64_windows
        uses: ./.github/actions/auto_gen_bind_pr
        with:
          build_target: x86_64-pc-windows-msvc
  generate_bind_x86_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: x86_windows
        uses: ./.github/actions/auto_gen_bind_pr
        with:
          build_target: i686-pc-windows-msvc
  generate_bind_x86_64_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: ./.github/actions/auto_gen_bind_pr
        with:
          build_target: x86_64-apple-darwin
